server:
  port: 89
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/bbs?useSSL=false&serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&socketTimeout=20000
      username: root
      password: RoOtPaSs
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 5
      initial-size: 1
      min-idle: 2
      max-wait: 60000
      time-between-eviction-runs-millis: 100000
      min-evictable-idle-time-millis: 300000
      poolPreparedStatements: true
      timeBetweenLogStatsMillis: 100000
      validationQuery: SELECT x
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxPoolPreparedStatementPerConnectionSize: 20
      #filters: stat,wall
      filters: stat,wall,log4j2
      filter:
        wall:
          config:
            multi-statement-allow: true
        stat:
          merge-sql: true
          # StatFilter属性slowSqlMillis用来配置SQL慢的标准，执行时间超过slowSqlMillis的就是慢。slowSqlMillis的缺省值为3000，也就是3秒。
          # 下面将 slowSqlMillis 修改为 5 秒，并且通过日志输出执行慢的SQL。
          log-slow-sql: true
          slow-sql-millis: 5000
      # 配置监控功能
      # WebStatFilter配置
      web-stat-filter:
        # 是否启用StatFilter默认值true
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        # 是否启用StatViewServlet默认值true
        enabled: true
        # 项目启动之后，访问：http://localhost:89/druid，会自动跳转至：http://localhost:89/druid/login.html，要求输入这里配置的用户名和密码
        url-pattern: /druid/*
        login-username: admin
        login-password: adminPass
        # IP白名单 (没有配置或者为空，则允许所有访问)
        allow: localhost
        # 禁用HTML页面上的“Reset All”功能
        resetEnable: false

# Web
spring.thymeleaf.prefix: classpath:/web/
#spring.thymeleaf
# Allow Thymeleaf web to be reloaded at dev time
spring.thymeleaf.cache: false

#logging.config: classpath:log4j2.xml
mybatis.config-location: classpath:mybatisConfig.xml
mybatis.mapper-locations: classpath*:bbs/api/biz/dal/mapper/xml/original/*.xml, bbs/api/biz/dal/mapper/xml/extend/*.xml
